
const String KEY_THEME = "THEME";
const String SIGNATURE = "c~chic_pass/a";
const String DATABASE_NAME = "chic_pass.db";

const categoryList = [
  "bank.png",
  "book.png",
  "business.png",
  "drawing.png",
  "education.png",
  "email.png",
  "food.png",
  "game.png",
  "health.png",
  "informatic.png",
  "science.png",
  "sport.png",
  "tv.png",
  "shopping.png",
  "stack_tweet.png",
  "collection_place.png",
  "document.png",
  "folder.png",
  "picture.png",
  "settings.png",
  "idea.png",
  "key.png",
  "music.png",
  "support.png",
  "puzzle.png",
  "religion.png",
  "chat.png",
  "wifi.png",
  "journal.png",
  "cloud.png",
  "car.png",
  "home.png",
  "trash.png",
];